GET http://localhost:4000/health
Content-Type: application/json

###

POST http://localhost:4000/api/v1/auth/register
Content-Type: application/json

{
    "username": "omor",
    "email":"omor12@gmail.com",
    "password": "omor1234"
}


###

POST http://localhost:4000/api/v1/auth/login
Content-Type: application/json

{
    "email":"omor11@gmail.com",
    "password": "omor1234"
}



###

POST http://localhost:4000/api/v1/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjUwMzlhMzc3MzVkYTMwMmI5ZWE3MiIsInVzZXJuYW1lIjoib21vciIsImVtYWlsIjoib21vcjEyQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMwNDc5MDE3LCJleHAiOjE3MzMwNzEwMTd9.mqu3Aqyd1I_kc-VVYYLnmyNYqBTDUAAb_MgNat7ZZmo

{
  "title": "Growing tgrough strugle",
  "author": "four",
  "description": "Atomic  Habits by James Clear is a comprehensive, practical guide on how to change your habits and get 1% better every day. Using a framework called the Four Laws of Behavior Change,",
  "genre": "self_help",
  "keywords": [
    "productive"
  ]
}

###

GET http://localhost:4000/api/v1/books
    ?page=3
    &limit=4
    # &sort_type=
    # &sort_by=
    # &search=
    # &sort_by=title
    # &sort_order=asc
    # &genre=self_help
    # &keywords=productive
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjFlYzhmODZlMDVjYjYzNjY0MTc1ZSIsInVzZXJuYW1lIjoib21vciIsImVtYWlsIjoib21vcjExQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMwMzA2NTQwLCJleHAiOjE3MzAzMTAxNDB9.FPNB01ejOLewBO7rMfcEkQJfMlTbngn0HTkKlJ2JBvA

###

GET http://localhost:4000/api/v1/books/67220aae54f76c42da7c03e0
Content-Type: application/json


###

PUT  http://localhost:4000/api/v1/books/67220aae54f76c42da7c03e0
Content-Type: application/json


###

PATCH  http://localhost:4000/api/v1/books/67220aae54f76c42da7c03e0
Content-Type: application/json

{
  "title": "dfdd",
   "genre":"atomic"
}
###

DELETE  http://localhost:4000/api/v1/books/507f1f77bcf86cd799439011
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjFlYzhmODZlMDVjYjYzNjY0MTc1ZSIsInVzZXJuYW1lIjoib21vciIsImVtYWlsIjoib21vcjExQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMwNDgwOTAxLCJleHAiOjE3MzMwNzI5MDF9.8OEWYq8e7mmmP8kStXh09cBsoM7Xeg2oruWJTk2i608
###

POST  http://localhost:4000/api/v1/borrow_books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MjFlYzhmODZlMDVjYjYzNjY0MTc1ZSIsInVzZXJuYW1lIjoib21vciIsImVtYWlsIjoib21vcjExQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzMwNDgwOTAxLCJleHAiOjE3MzMwNzI5MDF9.8OEWYq8e7mmmP8kStXh09cBsoM7Xeg2oruWJTk2i608